### ISSUE TITLE
The website can not open?

### ISSUE THREAD

**Issue by Code-kunkun** [lucas-ventura/CoVR#1]
I can't open the project website.

**Comment by lucas-ventura** [comment]
Hi @Code-kunkun,

It appears that the servers hosting the project website are currently down. As a solution, I've uploaded the project code to an alternative server. You can access the website using the following link: https://www.rocq.inria.fr/cluster-willow/lucasventura/covr/

This should allow you to access the project without any issues.

Best regards.

**Comment by Code-kunkun** [comment]
Thanks!!!
