### ISSUE TITLE
FashionIQ fine-tuned weights

### ISSUE THREAD

**Issue by hmd78** [lucas-ventura/CoVR#10]
Hi, Thanks for your great work.

Are you planning on releasing fine-tuned checkpoints for FashionIQ?

**Comment by lucas-ventura** [comment]
Hi, thanks for your interest!

I just uploaded the fine-tuned models for FashionIQ on Hugging Face. You can download the models by running:
```bash
git pull
bash tools/scripts/download_pretrained_models.sh 
Enter 4) FashionIQ
```

For testing, you can use the following commands:
```bash
python test.py test=fashioniq-dress model/ckpt=fashioniq-dress-ft_covr 
python test.py test=fashioniq-shirt model/ckpt=fashioniq-shirt-ft_covr 
python test.py test=fashioniq-toptee model/ckpt=fashioniq-toptee-ft_covr 
```

Hope this helps! Let me know if you have any further questions.

**Comment by hmd78** [comment]
thank you for your detailed and quick reply.

As I understood there are different checkpoints for each category.
Is there any reason that you didn't finetuned the model on whole dataset?

**Comment by lucas-ventura** [comment]
Hi,

My apologies, you're correct. I've now uploaded the checkpoint trained with the whole FashionIQ dataset.

To access the updated models, please follow these steps:
1. Run `git pull` to ensure you have the latest changes.
2. Execute `python tools/scripts/merge_fiq_annotations.py` to merge the annotations.
3. Use `bash tools/scripts/download_pretrained_models.sh` and select option 4 for FashionIQ.

After completing these steps, you can test the model using the following commands:
```bash
python test.py test=fashioniq-dress model/ckpt=fashioniq-all-ft_covr
python test.py test=fashioniq-shirt model/ckpt=fashioniq-all-ft_covr
python test.py test=fashioniq-toptee model/ckpt=fashioniq-all-ft_covr
```
The performance is better on all the three splits.

Thank you for bringing this to my attention. If you have any further questions or need assistance, please don't hesitate to ask.
