### ISSUE TITLE
Wget issue.

### ISSUE THREAD

**Issue by Agarciahunter** [lucas-ventura/CoVR#16]
Don't know if this is an issue on my end but wget is having this problem when I run it:

```
bash tools/scripts/download_pretrained_models.sh
Select the model to download:
1) All
2) WebVid-CoVR
3) CIRR
4) FashionIQ
Press Enter for default (All)
Enter your choice (1/2/3/4):
The ckpt_4.ckpt checkpoint already exists in outputs/webvid-covr/blip-large/blip-l-coco/tv-False_loss-hnnce_lr-1e-05/good/.
Do you want to overwrite? [y/N]: y
Downloading ckpt_4.ckpt checkpoint...
wget: unrecognized option '--show-progress'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Download failed.
The ckpt_5.ckpt checkpoint already exists in outputs/cirr/blip-large/webvid-covr/tv-False_loss-hnnce_lr-0.0001/base/.
Do you want to overwrite? [y/N]: y
Downloading ckpt_5.ckpt checkpoint...
wget: unrecognized option '--show-progress'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Download failed.
The ckpt_5.ckpt checkpoint already exists in outputs/fashioniq-all/blip-large/webvid-covr/tv-False_loss-hnnce_lr-0.0001/base.
Do you want to overwrite? [y/N]: y
Downloading ckpt_5.ckpt checkpoint...
wget: unrecognized option '--show-progress'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Download failed.

```

Don't know if this a problem on my end. Getting rid of `-show-progress` did fix it though.

**Comment by lucas-ventura** [comment]
I just tested this on a new setup and it’s working fine for me. It seems the error you're seeing might be related to the version of ``wget`` you are using, which does not recognize the ``--show-progress`` option. You can check for similar issues and their resolutions, such as the one discussed here: [github issue](https://github.com/backdrop-contrib/bee/issues/207).

As a workaround, you could manually download the files using the URLs provided in the [download_pretrained_models.sh](https://github.com/lucas-ventura/CoVR/blob/master/tools/scripts/download_pretrained_models.sh) script and then use ``scp`` to transfer them to the correct directory in your machine.

Hope this helps!
