### ISSUE TITLE
What is the search space for a query in test set??

### ISSUE THREAD

**Issue by h-pal** [lucas-ventura/CoVR#17]
Hi,
I am slightly confused about the test set's search space. Given a query (Image/video and text) from the test set, what is the search space for this query? I am assuming that we are searching over all the possible target videos in the test set. I'd appreciate it if you could confirm this.
Thanks

**Comment by lucas-ventura** [comment]
Hi, 

It depends on the dataset:
- For **WebVid-CoVR**, the search space includes all target embeddings specified in [``ann["path2"]``](https://github.com/lucas-ventura/CoVR/blob/1d152b952232e4cc91609525b095e1272c17d478/src/data/webvid_covr.py#L297C26-L297C38).
- For **CIRR**, the search space consists of all images in the [target embedding folder](https://github.com/lucas-ventura/CoVR/blob/1d152b952232e4cc91609525b095e1272c17d478/src/test/cirr.py#L79), which includes the embeddings from the test set directory images.
- For **FashionIQ**, the search space is defined by [``target_ids``](https://github.com/lucas-ventura/CoVR/blob/1d152b952232e4cc91609525b095e1272c17d478/src/test/fashioniq.py#L83), which correspond to the ids from the [targets split json file](https://github.com/lucas-ventura/CoVR/blob/1d152b952232e4cc91609525b095e1272c17d478/configs/data/fashioniq-base.yaml#L16).

Hope this clarifies things!
