### ISSUE TITLE
please provide feature file

### ISSUE THREAD

**Issue by May2333** [lucas-ventura/CoVR#2]
Hi,
  thanks for your great work!
  But this dataset is too large to download, can you provide the blip feature file?
  Any reply will be helpful!

**Comment by lucas-ventura** [comment]
Hi @May2333,

Thank you! What blip feature file are you referring to? Have you tried downloading the available one using `bash tools/scripts/download_pretrained_models.sh`? If you want to use a different one, I can upload it for you.

Best,
Lucas

**Comment by thechargedneutron** [comment]
Hi @lucas-ventura , I am looking for the best checkpoint on webvid-covr, can you please provide that as well? Also when I run `python test.py test=webvid-covr` using the available checkpoint at `outputs/webvid-covr/blip-large/blip-l-coco/tv-False_loss-hnnce_lr-1e-05/good/ckpt_4.ckpt` I get low performance as follows:

```
{'R1': 15.85, 'R5': 32.79, 'R10': 40.3, 'R50': 58.37, 'meanR3': 29.64, 'meanR4': 36.
83, 'annotation': 'webvid8m-covr_test.csv'}
```

Am I using the wrong checkpoint or do I need to change some configs to see the performance reported in the paper?

**Comment by lucas-ventura** [comment]
Hi @thechargedneutron,

The default checkpoint for ``python test.py`` is ``blip-l-coco.yaml`` which corresponds to the BLIP pretrained model (see default ``model/ckpt`` [line](https://github.com/lucas-ventura/CoVR/blob/master/configs/test.yaml#L21C17-L21C28) in ``test.yaml``). This is why you're observing the zero-shot performance, as mentioned in the first row of Table 5 in our paper.

To use the `outputs/webvid-covr/blip-large/blip-l-coco/tv-False_loss-hnnce_lr-1e-05/good/ckpt_4.ckpt` checkpoint, please run the following command:
```bash
python test.py test=webvid-covr model/ckpt=webvid-covr
``` 

For the best checkpoint on CIRR, you can use this command:
```bash
python test.py test=cirr model/ckpt=cirr_ft-covr+gt
```

Before executing these commands, make sure you have both models downloaded by running:
```bash
bash tools/scripts/download_pretrained_models.sh overwrite
```

Let me know if you have any more questions or need further assistance.
