### ISSUE TITLE
Issues with the CC-CoIR Dataset

### ISSUE THREAD

**Issue by ChenAnno** [lucas-ventura/CoVR#22]
Hi, thank you for your valuable work in this field! 
I would like to inquire about the new dataset CC-CoIR constructed in your TPAMI paper: 

1. It seems that the file downloaded from [https://github.com/lucas-ventura/CoVR/blob/c9423a0e122d2bd1676587d6d2498540c13a6a42/tools/scripts/download_annotation_coir.sh#L12](url) is a ckpt file. 
2. I notice that [https://huggingface.co/datasets/lucas-ventura/CC-CoIR](url) provides annotation files, but I would like to know the correspondence between the pth1 and pth2 domains and the CC3M dataset file names (e.g., 000430543.jpg). 

Thank you very much for your response!

**Comment by lucas-ventura** [comment]
Hi, thank you for your interest and for catching that!

You're absolutely right—apologies for the confusion. I've just updated the URL in my latest commit (287bc19) to point to the correct CSV file. You can visualize the dataset here: [CC-CoIR dataset on Hugging Face](https://huggingface.co/datasets/lucas-ventura/CC-CoIR).

To download the dataset, you can now use the following commands:
```bash
git switch covr2
git pull
bash tools/scripts/download_annotation_coir.sh   
```

With the correct CSV file, your questions regarding `pth1` and `pth2` should be resolved. They are now formatted like this: `26/5485b84160ccdf4e525f7d2e2cfa8cec2c3d06dc`, corresponding to the CC3M file names.

Feel free to reach out if you have any further questions!

**Comment by ChenAnno** [comment]
Hi Lucas, thank you so much for your quick response! 
Could you please share details on how to download and process the CC3M dataset? I followed a common method: [https://github.com/ray-ruisun/CC3M-Helper/](https://github.com/ray-ruisun/CC3M-Helper/), but I couldn't obtain the CC3M file names from the CSV file. 
Thanks a lot!

**Comment by lucas-ventura** [comment]
I actually didn’t download CC3M myself, as it was already installed in my cluster. For reference, in the ``Train_GCC-training.tsv`` file from CC3M, the ``pth`` column matches the ``pth1`` and ``pth2`` columns in ``cc-coir_train.csv`` from CC-CoIR, with just a small difference: the CC3M file paths are formatted as ``"train/{pth}.jpg"``.

To retrieve the paths used in CC-CoIR, you can do something like this:
```python
coir_pth = "path/to/CoVR/annotation/cc-coir/cc-coir_train.csv"
df_coir = pd.read_csv(coir_pth)
coir_imgs = set(df_coir["pth1"].unique()) | set(df_coir["pth2"].unique())
coir_pths = [f"train/{pth}.jpg" for pth in coir_imgs]
````

Then, you can match these paths with the CC3M dataset like this:
```python
cc_pth = "path/to/Train_GCC-training.tsv"
df_cc = pd.read_csv(cc_pth, sep="\t", header=None)
df_cc.columns = ["caption", "url", "pth"]
df_cc = df_cc.dropna(subset=["pth"])
df_cc = df_cc[df_cc["pth"].isin(coir_pths)]
```

This should help you filter down to the CC3M paths that correspond to the images used in CC-CoIR.

**Comment by ChenAnno** [comment]
Hi Lucas, thank you so much for your prompt and detailed response! 
I seem to have found the issue: the Train_GCC-training.tsv file downloaded from the CC3M [official website](https://ai.google.com/research/ConceptualCaptions/download) only has the "caption" and "url" columns, **without the "pth" column**. Could you please share your Train_GCC-training.tsv? 
Sorry for bothering you on the weekend, hope you have a great weekend :)

**Comment by lucas-ventura** [comment]
Hi! I’ve just uploaded [`cc-coir_urls.csv`](https://huggingface.co/datasets/lucas-ventura/CC-CoIR/blob/main/cc-coir_urls.csv) on Hugging Face. This file is a filtered version of `Train_GCC-training.tsv`, containing only the paths used in CC-CoIR, with `caption`, `url`, and `pth`.

No problem at all! Hope you have a great weekend too :)

**Comment by ChenAnno** [comment]
Thank you so much, Lucas!
