### ISSUE TITLE
Issue with webvid-covr dataset

### ISSUE THREAD

**Issue by Jasmine-tjy** [lucas-ventura/CoVR#23]
Dear lucas, I'm really interested in your work, but when I use “bash tools/scripts/download_annotation.sh covr” to download the annotation of webvid-covr dataset, it seems always an empty directory without any downloading error. I wonder is it correct? 
![dataset](https://github.com/user-attachments/assets/22869014-8aa9-4adb-9a68-70771e59ac7d)

**Comment by lucas-ventura** [comment]
Hi,

Thanks for your interest! 

I just merged the latest ``covr`` branch, and I tested it in a fresh repository where it worked as expected. Could you please try again after doing a ``git pull``? Let me know if you still encounter any issues.

**Comment by Jasmine-tjy** [comment]
I tried agian and it wroked! thanks a lot!

**Comment by Jasmine-tjy** [comment]
Dear lucas, thanks for your quick response. When I download the webvid-covr dataset with “split=test” and then do the compute BLIP embeddings everything goes well, but when I try the test.py, it always occurs something wrong as
"Missing 176 pth1's (7.2%), saving them to missing_pth1-test.txt
Error executing job with overrides: []
Error in call to target 'src.data.webvid_covr.WebVidCoVRTestDataModule':
ValueError("Missing 176 pth1's (7.2%) in test split")
full_key: test.webvid_covr"
or 
"Missing 29 pth1's (1.2%), saving them to missing_pth1-test.txt
Error executing job with overrides: []
Error executing job with overrides: []
Error in call to target 'src.data.webvid_covr.WebVidCoVRTestDataModule':
ValueError("Missing 29 pth1's (1.2%) in test split")
full_key: test.webvid_covr"
and also I cannot find the missing_pth1-test.txt file, could you give some advice to solve this problem？
