### ISSUE TITLE
readme file error

### ISSUE THREAD

**Issue by HouTong-s** [lucas-ventura/CoVR#3]
to download the annotation files,
the file says to "bash tools/scripts/download_annotations.sh covr"
however, the file name is download_annotation.sh
so, it should be bash tools/scripts/download_annotation.sh covr
where there is no s in the end

**Comment by lucas-ventura** [comment]
Hi @HouTong-s,

Yes, thank you! I fixed this yesterday, you can `git pull` to get the correct version.
