### ISSUE TITLE
readme issues

### ISSUE THREAD

**Issue by HouTong-s** [lucas-ventura/CoVR#4]
I said it is "bash tools/scripts/download_annotations.sh cirr"  and "bash tools/scripts/download_annotations.sh fiq" that hve an additional 's' at the end of the word.

**Comment by lucas-ventura** [comment]
You're correct, I missed the 's' in fiq and cirr. Thank you for pointing that out! I've fixed the typo in the latest [commit](https://github.com/lucas-ventura/CoVR/commit/b6fca9e8419005502a959eece507fd17586b852d).
