### ISSUE TITLE
fashionIQ datasets class issue

### ISSUE THREAD

**Issue by HouTong-s** [lucas-ventura/CoVR#7]
in the configs/test/fashioniq-dress(shirt or toptee).yaml
there is
targets: ${paths.work_dir}/annotation/fashion-iq/split.toptee.val.json

however the split.toptee.val.json file doesn't exist 

can i get a split.toptee.val.json from you?

**Comment by lucas-ventura** [comment]
Hi @HouTong-s, thanks for bringing this up.

The missing `split.toptee.val.json` issue has been resolved in the [latest commit](https://github.com/lucas-ventura/CoVR/commit/ed1575a637940077a0e6e4d3dc3e9bd3ddb10eb6). You can obtain the missing split files with:

```bash
bash tools/scripts/download_annotation.sh fiq
```

Please give it a try, and let me know if you encounter any further issues.

**Comment by HouTong-s** [comment]
> Hi @HouTong-s, thanks for bringing this up.
> 
> The missing `split.toptee.val.json` issue has been resolved in the [latest commit](https://github.com/lucas-ventura/CoVR/commit/ed1575a637940077a0e6e4d3dc3e9bd3ddb10eb6). You can obtain the missing split files with:
> 
> ```shell
> bash tools/scripts/download_annotation.sh fiq
> ```
> 
> Please give it a try, and let me know if you encounter any further issues.

I got that json file in the repository of the origin fashionIQ author
and I think your code correction will works.
