### ISSUE TITLE
Dataset download paths not working

### ISSUE THREAD

**Issue by thechargedneutron** [lucas-ventura/CoVR#8]
Great work! I see that the urls path is not working [http://imagine.enpc.fr/~ventural/covr/dataset/webvid8m-covr_paths-test.json](http://imagine.enpc.fr/~ventural/covr/dataset/webvid8m-covr_paths-test.json). Can you please update that?

**Comment by lucas-ventura** [comment]
Hi @thechargedneutron, sorry for that. Can you try now?

**Comment by thechargedneutron** [comment]
Thanks, works now
